# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Git/radio_periph_lab/vivado/radio_periph_lab.srcs/sources_1/bd/design_1/ip/design_1_simple_fifo_0_1/design_1_simple_fifo_0_1.xci
# IP: The module: 'design_1_simple_fifo_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Git/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_simple_fifo_0_1/src/axis_data_fifo_0/axis_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# IP: D:/Git/radio_periph_lab/vivado/radio_periph_lab.srcs/sources_1/bd/design_1/ip/design_1_simple_fifo_0_1/design_1_simple_fifo_0_1.xci
# IP: The module: 'design_1_simple_fifo_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Git/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_simple_fifo_0_1/src/axis_data_fifo_0/axis_data_fifo_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet
