# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Git/radio_periph_lab/ip_repo/full_radio/src/dds_tuner/dds_tuner.xci
# IP: The module: 'dds_tuner' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Git/radio_periph_lab/ip_repo/full_radio/src/dds_tuner/dds_tuner_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_tuner'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Git/radio_periph_lab/ip_repo/full_radio/src/dds_tuner/dds_tuner.xci
# IP: The module: 'dds_tuner' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Git/radio_periph_lab/ip_repo/full_radio/src/dds_tuner/dds_tuner_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_tuner'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
