# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Git/radio_periph_lab/ip_repo/full_radio/src/fir2_3125/fir2_3125.xci
# IP: The module: 'fir2_3125' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Git/radio_periph_lab/ip_repo/full_radio/src/fir2_3125/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir2_3125'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Git/radio_periph_lab/ip_repo/full_radio/src/fir2_3125/fir2_3125_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir2_3125'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Git/radio_periph_lab/ip_repo/full_radio/src/fir2_3125/fir2_3125.xci
# IP: The module: 'fir2_3125' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Git/radio_periph_lab/ip_repo/full_radio/src/fir2_3125/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir2_3125'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Git/radio_periph_lab/ip_repo/full_radio/src/fir2_3125/fir2_3125_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir2_3125'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
