# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Git/radio_periph_lab/vivado/radio_periph_lab.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1.xci
# IP: The module: 'design_1_auto_cc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Git/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_cc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Git/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_cc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Git/radio_periph_lab/vivado/radio_periph_lab.srcs/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1.xci
# IP: The module: 'design_1_auto_cc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Git/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_cc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Git/radio_periph_lab/vivado/radio_periph_lab.gen/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_cc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
